version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" # local 80 port map to container 80 port
    environment:
      - NODE_ENV=production
    restart: always